### ISSUE TITLE
More Options to Configure While Shuffling the Deck

### ISSUE THREAD

**Issue by spxctreofficial** [deck-of-cards/standard-deck#8]
As a virtual Poker card simulator, I can say that this is amazing. One thing I do wish would be included however, would be the ability to configure the shuffling settings. Currently, when shuffling, you take the cards from the players back into the deck while shuffling, and I was wondering if it was possible to have a toggle to turn that off.

**Comment by pakastin** [comment]
That is coming yeah 👍
